name: Build Python Executable

on:
  push:
    branches:
      - main  # 当代码推送到main分支时触发
      - master # 也支持master分支
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --name plate_mosaic_ocr --onefile --clean app.py
        shell: powershell
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plate-mosaic-ocr-windows-exe
          path: dist/plate_mosaic_ocr.exe